---
-
  hosts: all

  roles:
    #- debian
    - shared

  vars:
    postgresql:
      version: 9.1
      password: postgres
    database: library_development
    proxy_env:
      LC_ALL: en_US.UTF-8
      LC_LCTYPE: en_US.UTF-8
      LC_MESSAGES: POSIX

  tasks:

    -
      name: install packages
      apt: pkg={{ item }} state=installed update_cache=yes force=yes
      sudo: true
      environment: proxy_env
      with_items:
       - python-psycopg2
       - python-pycurl
       - python-apt
       - postgresql-{{postgresql.version}}
       - libpq-dev
       - imagemagick

    -
      name: install RVM and Ruby
      shell: curl -sSL https://get.rvm.io | bash -s stable --ruby=2.1.0 --autolibs=enabled --rails
        creates=~/.rvm/rubies/ruby-2.1.0/bin/ruby

    -
      name: update postgres client configuration
      sudo: true
      copy: src=files/pg_hba.conf dest=/etc/postgresql/{{postgresql.version}}/main/pg_hba.conf
      notify:
        - restart postgresql

    -
      meta: flush_handlers

    -
      name: create postgresql user postgres
      postgresql_user:
        name=postgres
        password={{ postgresql.password}}

    -
      name: create dev db
      postgresql_db:
        name={{ database }}

  handlers:
    -
      name: restart postgresql
      sudo: true
      service: name=postgresql state=restarted
